name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          printf '%s\n' "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ls -la ~/.ssh/id_rsa
          
      - name: Deploy to EC2
        env:
          HOSTNAME: ${{ secrets.EC2_HOST }}
          USER_NAME: ubuntu
        run: |
          # プロジェクトファイルをEC2にコピー
          scp -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -i ~/.ssh/id_rsa -r public server.js package.json ${USER_NAME}@${HOSTNAME}:/home/ubuntu/hello-vibe/
          
          # サーバーをセットアップして起動
          ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -i ~/.ssh/id_rsa ${USER_NAME}@${HOSTNAME} '
            cd /home/ubuntu/hello-vibe
            npm install --production
            pm2 delete hello-vibe || true
            pm2 start server.js --name hello-vibe
            pm2 save
            echo "✅ デプロイ完了！"
          '

